### ISSUE TITLE
When evaluating, the file path cannot be found.

### ISSUE THREAD

**Issue by 1304150468** [TianyuGoGO/XPNG#1]
Hello, when I was reproducing your code, I encountered an error during evaluation, which indicated that 'datasets/coco/annotations/instances_val2017.json' could not be found. It seems that this file was not required to be downloaded, and the path is also inconsistent with the configuration in the readme. What could be the reason for this?
python：3.9.19，cudatoolkit：11.1.1，pytorch：1.10.1
![image](https://github.com/TianyuGoGO/XPNG/assets/106361049/2c09c171-cc0a-487c-a46a-4f411b74f7f0)
![image](https://github.com/TianyuGoGO/XPNG/assets/106361049/a5db6bfa-23d7-4101-b0e8-c746e204a3a5)

I hope you can help me solve this problem. Thank you.

**Comment by TianyuGoGO** [comment]
You can download the missing resources through this website https://huggingface.co/datasets/merve/coco/blob/main/annotations/instances_val2017.json

2024-04-20 15:03:13 "1304150468" ***@***.***> 写道：

Hello, when I was reproducing your code, I encountered an error during evaluation, which indicated that 'datasets/coco/annotations/instances_val2017.json' could not be found. It seems that this file was not required to be downloaded, and the path is also inconsistent with the configuration in the readme. What could be the reason for this?
python：3.9.19，cudatoolkit：11.1.1，pytorch：1.10.1
image.png (view on web)
image.png (view on web)

I hope you can help me solve this problem. Thank you.
